### ISSUE TITLE
Move to VaporJWT 0.6 to support production builds

### ISSUE THREAD

**Issue by cwoloszynski** [matthijs2704/vapor-apns#19]
Building production code fails when using VaporJWT 0.5.  

% vapor build --release fails on MacOS with 0.5.1

Can you please update the package to use 0.6?

**Comment by matthijs2704** [comment]
Done! :) Thanks @siemensikkema

**Comment by cwoloszynski** [comment]
Thanks!  You and Siemens make a great team (and my life really easy)!

Much appreciated.  One step closer to having a project ready for production release!
