### ISSUE TITLE
[Question] This is compatible with push kit?

### ISSUE THREAD

**Issue by gperdomor** [matthijs2704/vapor-apns#24]
Hi...

I tried to send a notification using a push kit token and always return "Pushing to this topic is not allowed"

**Comment by matthijs2704** [comment]
Hey
What topic are you using? The topic must be your App ID, otherwise Apple won't allow you to push to it ;)

**Comment by gperdomor** [comment]
Yes, I know, I send two notifications, one with a normal push token and other with push kit token to the same topic/app Id...

Only work the normal push token

**Comment by matthijs2704** [comment]
Could you specify what you mean with PushKit? You mean for VOIP applications or? Could you send the link to the Apple Documentation for it? I can't seem to find what you mean...

**Comment by gperdomor** [comment]
I use a voip cert and a .p8 key but in both cases fails...

PushKit is a framework (https://developer.apple.com/reference/pushkit) to handle notifications

**Comment by matthijs2704** [comment]
Yeah, I see, so it's for VoIP apps.

You need to make sure you are using the right certificate for sending to that topic. I'm not sure if the new p8 key way supports PushKit yet... Use the old certificate way with the VoIP/PushKit certificate instead of the p8 file.

I haven't worked with VOIP payloads yet, so I don't have any experience with PushKit. Reading through other APNS apps, it seems like PushKit is automatically supported, provided that you're using the correct certificates

**Comment by matthijs2704** [comment]
You will need to have to use https://github.com/matthijs2704/vapor-apns#-certificate-authentication

**Comment by gperdomor** [comment]
My tests was:

### With VOIP Cert:

- PushKit Token and Sandbox = true: Pushing to this topic is not allowed.
- PushKit Token and Sandbox = false: The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.

- Normal Push Token and Sandbox = true: The device token does not match the specified topic.
- Normal Push and Sandbox = false: The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.

### With P8 Key:

- PushKit Token and Sandbox = true: Pushing to this topic is not allowed.
- PushKit Token and Sandbox = false: The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.

- Normal Push Token and Sandbox = true: Success.
- Normal Push and Sandbox = false: The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.

**Comment by gperdomor** [comment]
The certs are valid, in facts, y use the same voip certs and key that we use with sygnal (a push gateway for matrix server build with python).

My goal is port sygnal to swift but my project not work with the Pushkin token :(

**Comment by matthijs2704** [comment]
Update on my previous message: PushKit does _not_ support Authentication Tokens, you must use certs. 

Have you installed it on your mac, then exported it with your private key as p12 and then converted it like I described in the README? (Like normal push certs) Passing the cert you got from apple won't work. But by the way for that project you don't need VoIP services right? Normal push certifications aren't enough?

**Comment by gperdomor** [comment]
### With Normal Push Cert:

- PushKit Token and Sandbox = true: The device token does not match the specified topic.
- PushKit Token and Sandbox = false: Error in the HTTP2 framing layer.

- Normal Push Token and Sandbox = true: success.
- Normal Push and Sandbox = false: Error in the HTTP2 framing layer.

**Comment by matthijs2704** [comment]
No, you need the VoIP certs if you want to send PushKit messages....

**Comment by gperdomor** [comment]
Yes, the certs are exported as you describe in the readme... At this stage, the normal push is enough but the idea is that the project also support voip tokens

**Comment by matthijs2704** [comment]
And "The device token does not match the specified topic." indicates that you're sending to the wrong device token as well. 

Try this: send a push notification with VoIP certificates, to your VoIP topic, to a device which is registered (setup a test app on iOS, copy the registration token and send it to that. Don't use the registeredForRemoteNotification callback for that, as you're sending to VoIP ;).)

**Comment by gperdomor** [comment]
I test with three options, the VOIP Certs, the normal Certs and the P8 Key, only works with normal tokens

**Comment by gperdomor** [comment]
I have both tokens, the normal and the pushkit...

I use the PushToken and a VOIP Cert to send a notification using Knuff (https://github.com/KnuffApp/Knuff) and works...

I use the same pushkit token and the same VOIP Cert with sygnal (https://github.com/matrix-org/sygnal) and works.

And also use the same pushkit token and the same VOIP Cert with VaporAPNS and fails

**Comment by matthijs2704** [comment]
Found it! I setup a small test project to test it :)

You need to add `.voip` to the topic. So if your bundleid is `com.matthijs2704.callDemo`, your topic should be `com.matthijs2704.callDemo.voip`

**Comment by gperdomor** [comment]
:D works...

Where found it? XD

**Comment by matthijs2704** [comment]
Awesome! Well I was just testing some things and reading through some documentation ;)
Read about the VoIP notifications being extra important, so they are handled separately by Apple, which means they should have a way to identify the VoIP messages. So I thought, let's add a `.voip` prefix 😃 

Maybe I will make some sort of Q&A page later, so people getting this problem later on they can reference to this.

**Comment by gperdomor** [comment]
Thanks, remember add that to the readme :D

**Comment by saroar** [comment]
@gperdomor can you share your code for VoIP please I am trying to create an app where I need VoIP notification for calling
