### ISSUE TITLE
[Feature] configure Certs and Keys from env vars

### ISSUE THREAD

**Issue by gperdomor** [matthijs2704/vapor-apns#25]
Hi...

Have you thought about adding support for configuring certificates or auth key from environment variables? I mean putting the contents of the files in the environment variable, this way it could work on services with ephemeral storage like heroku

**Comment by matthijs2704** [comment]
No it's not something I am going to implement in the library. Those kind of stuff should be handled in the application using the library. When using Vapor, you can use Configs. For heroku, you'll need to do more than just that as HTTP/2 isn't supported on buildpack. Check this: https://github.com/matthijs2704/vapor-apns/issues/16
