### ISSUE TITLE
NetworkError(VaporAPNS.SimpleError.string("Failure when receiving data from the peer"))

### ISSUE THREAD

**Issue by mcdappdev** [matthijs2704/vapor-apns#26]
When trying to send a push notification, I get the above error.

**Comment by matthijs2704** [comment]
This means that you've installed an old version of curl or the installed version of curl doesn't support HTTP/2. You can update and build from source yourself or you can use the installer included in the prerelease version (works for Ubuntu and macOS)

**Comment by mcdappdev** [comment]
So I should just update my Package.swift to the prerelease version? Will that fix it?

**Comment by matthijs2704** [comment]
That'll give you the option to update curl, yes. Not everyone likes that feature, so not a real release yet...

**Comment by mcdappdev** [comment]
When does it give you the option to update curl? Sorry for the noob questions

**Comment by matthijs2704** [comment]
Haha no problem! Build and run ;) Instead of starting the vapor server, it'll say something like "CUrl is out of date, do you want to update?", then just type 'y' and it'll build a compatible version of from source and it'll install it on your system :)

**Comment by mcdappdev** [comment]
Oh awesome!! Thank you so much :)

**Comment by mcdappdev** [comment]
So I just run `vapor run --release` and it'll ask me to update? It didn't do that :(

**Comment by matthijs2704** [comment]
Did you run `vapor clean` before building? what does `curl --version` say?

**Comment by matthijs2704** [comment]
Oh wait, you need to run `vapor build --run` not just `vapor run` as that'll just run the old build of your app ;)

**Comment by mcdappdev** [comment]
Ahhhhh, I'll try that. Thank you!!

**Comment by mcdappdev** [comment]
Ok, that worked. I should only have to do that once, right?

**Comment by matthijs2704** [comment]
Yep! It won't ask you again anyways :)
