### ISSUE TITLE
I'm seeing a "Failure when receiving data from the peer" error when using token based auth

### ISSUE THREAD

**Issue by waterskier2007** [matthijs2704/vapor-apns#38]
I'm seeing this error after following the docs line-for-line. I am not sure what is causing the error though. Has anyone else seen this?

**Comment by matthijs2704** [comment]
This means that the curl is installed but it's HTTP2 extention isn't. Try using the installer included in version 1.2

**Comment by waterskier2007** [comment]
@matthijs2704 installer in what version 1.2? version 1.2 of brew? the instructions specify installing curl through brew and that's what i followed

**Comment by matthijs2704** [comment]
No in version 1.2 of VaporAPNS (it now includes an installer)

**Comment by waterskier2007** [comment]
Where can this installer be found? thanks for the help by the way

**Comment by matthijs2704** [comment]
Replace `minor: 1` with `minor: 2`, then run your project in Terminal (`vapor build --run`). If the version is incorrect it'll show steps to update curl

**Comment by waterskier2007** [comment]
ah, thanks!
