### ISSUE TITLE
Add way to mass send push notifications

### ISSUE THREAD

**Issue by matthijs2704** [matthijs2704/vapor-apns#4]
Add a way to send push notifications to an array of device tokens.

**Comment by alexaubry** [comment]
Hi! As I need this feature for my own server, I've been thinking about a way to do it and I came up with this idea :

Making `ApplePushMessage` device-independent (i.g. removing the `deviceToken` property) would enable the renaming of this method to send the notification to one device :

```swift
VaporAPNS.send(applePushMessage:deviceToken:) -> Result
```

This renamed method would make the implementation of the batch-send feature pretty easy :

```swift
VaporAPNS.send(applePushMessage:deviceTokens:perDeviceCompletionHandler:)
```

`deviceTokens` is an array of device tokens.
`perDeviceCompletionHandler` is a closure (`(ApplePushMessage,String,Result)->Void`) that is called once for every device with the send result for that device.

The method calls `send(applePushMessage:deviceToken:)` for every token in the array and then calls the closure with the message, token and result.

This design has been inspired by CloudKit's operations completion handlers (ex: [CKFetchRecordsOperation](https://developer.apple.com/reference/cloudkit/ckfetchrecordsoperation/1476082-perrecordcompletionblock))

Of course this would be a source-breaking change 😬

I have a draft implementation in my fork's [batch-send branch](/alexaubry/vapor-apns/tree/batch-send).

Tell me what you think about it!

**Comment by matthijs2704** [comment]
@alexaubry Thanks! I was already working on something similar indeed :P 

This was added in VaporAPNS 1.1.0

**Comment by matthijs2704** [comment]
It is still all sync, so If you want to do it async, just use libdispatch or something similar :)
