### ISSUE TITLE
Update to Vapor 2.0

### ISSUE THREAD

**Issue by jimmya** [matthijs2704/vapor-apns#43]
Since Vapor is updated to 2.0 it would be nice to update Vapor APNS to support Vapor 2.0.
I've checked the dependencies and it seems a lot of the dependencies have already been updated. The only remainder currently is https://github.com/vapor/jwt.git but it seems to be in the process of updating.

**Comment by mludi** [comment]
VaporJWT is Vapor 2 ready!

**Comment by matthijs2704** [comment]
Thanks @jimmya. Yeah I know that I need to update to Vapor 2.0 😛 , but as I've said before in the Slack, I'm really busy currently with my high school finals, so haven't really found the time to work on it yet. Last one is coming up this Tuesday, so I'm hoping I can get working on this really soon!

**Comment by jimmya** [comment]
I'm eager to help so I've made some commits in my fork to get things working. It's compiling now and tests are succeeding. I think however the code code be improved in some more places to make things more in line with Vapor 2.0.
