### ISSUE TITLE
Fails to find brew

### ISSUE THREAD

**Issue by kylebrowning** [matthijs2704/vapor-apns#47]
Im not sure why but, 

```swift

// MARK: - Homebrew (macOS)
    private func checkBrewInstalled() -> Bool {
        let (_, result) = shell("which", arguments: ["-s", "brew"])
        return result == 0
    }

```

fails to find my brew,
```
kylebrowning at Kyles-MacBook-Pro in ~/work/swift/Hello on master [+!?]
$ which brew
/usr/local/bin/brew
```

**Comment by kylebrowning** [comment]
I worked around it by cancling the check.

**Comment by matthijs2704** [comment]
You shouldn’t cancel the check. This way the wrong version of curl stays installed on your system and VaporAPNS won’t work

**Comment by kylebrowning** [comment]
I compiled brew myself with the nghttp2 and open ssl options.

**Comment by matthijs2704** [comment]
Have you also linked over the system curl?

**Comment by kylebrowning** [comment]
Since the updater thinks I dont have homebrew installed, which I do, I compiled it myself using, 

` brew install curl --with-openssl --with-nghttp2`

Then I manually linked to that library using....
```
LDFLAGS:  -L/usr/local/opt/curl/lib
CPPFLAGS: -I/usr/local/opt/curl/include
```

**Comment by matthijs2704** [comment]
No no, not that linking. Lemme find the command. It’s also in the updater

**Comment by kylebrowning** [comment]
Oh, brew link?

**Comment by kylebrowning** [comment]
`brew link curl --force`

**Comment by matthijs2704** [comment]
Exactly

**Comment by kylebrowning** [comment]
Yes I did, still fails. cleaned build as well.

**Comment by matthijs2704** [comment]
Run ‘vapor xcode’ again

**Comment by kylebrowning** [comment]
Thanks, that worked.

**Comment by matthijs2704** [comment]
Awesome, good luck
