### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by kylebrowning** [matthijs2704/vapor-apns#48]
fatal error: unexpectedly found nil while unwrapping an Optional value

```swift
let str = String.init(data: writeStorage.data, encoding: .utf8)!
```

**Comment by matthijs2704** [comment]
That’s exactly what the updater solves

**Comment by kylebrowning** [comment]
Whats the updater? Can you point me in the right direction?

**Comment by kylebrowning** [comment]
Oh i see the curl updater.
