### ISSUE TITLE
Vapor 2.0

### ISSUE THREAD

**Issue by fabrijp** [matthijs2704/vapor-apns#49]
Will it be compatible with new Vapor 2.0~ ?

**Comment by matthijs2704** [comment]
Already is, haven’t gotten around to fix the README yet

**Comment by fabrijp** [comment]
I see. I’m just trying to add it to a new and clean project ( Vapor 2.1 ) and it just won’t build after add the VaporAPNS package..

**Comment by fabrijp** [comment]
It gives this error:
Could not generate Xcode project: swift-package: error: unsatisfiable

**Comment by fabrijp** [comment]
Aha! just saw now that there is a version 2 !  i was following the readme docs that stills talking about version 1.2..
Just replace the majorVersion to 2 and now it works.

Thanks!
