### ISSUE TITLE
silent remote notification doesn't work

### ISSUE THREAD

**Issue by carlhung** [matthijs2704/vapor-apns#52]
I tried to send silent notification but not lucky enough it doesn't work on me.
I have looked around I saw `makeJSON` method in Payload class that `contentAvailable` property that if it is true, then it would be `apsPayloadData["content-available"] = true`. but as I know, it should be 1.
anyway, even I change to 1, it still doesn't work on me.

**Comment by matthijs2704** [comment]
True is the same as entering 1, but true looks cleaner. Make sure you are not sending an alert in the payload as that defeats the purpose of the silent notification. I've tried it myself and it works fine so the issue does not lay with the library
