### ISSUE TITLE
Memory increasing after each notification

### ISSUE THREAD

**Issue by fabrijp** [matthijs2704/vapor-apns#54]
I have notice that the App memory is always increasing ( ~ 1MB in my case ) after each Content Available sent push.

I'm working on a Vapor 1.5.15 project with vaporAPNS 1.2.2

**Comment by fabrijp** [comment]
Doing some tests I may found a workaround ( maybe a solution? ) adding a call to clean-up the curlHandle on the send method in VaporAPNS.swift just after the for loop.

```
open func send(_ message: ApplePushMessage, to deviceTokens: [String], perDeviceResultHandler: ((_ result: Result) -> Void)) {
        for deviceToken in deviceTokens {
            let result = self.send(message, to: deviceToken)
            perDeviceResultHandler(result)
        }

        // Clean-up curl to avoid memory leak
        curl_easy_cleanup(curlHandle)
    }
```

**Comment by matthijs2704** [comment]
This is intended behaviour. There is no cleanup call as that will end the handle and close the connection with the servers, therefore opening many new connections to the APNS server for every notification. Now the connection is reused for all notifications and cleanup is handled by the system AFAIK

**Comment by fabrijp** [comment]
I see. Thanks for the reply! I was also getting a curl timeout crash when sending few thousands push to a dozen devices a day and the cleanup solves the issue. Maybe a timed cleanup or by push volume should be better to implement. Of course that’s in my case only.

**Comment by matthijs2704** [comment]
A few thousand at a time? If so, for a few thousand pushes it is much better to create multiple instances of VaporAPNS and split it up to send using more connections simultaneously, this will be a lot quicker also

**Comment by fabrijp** [comment]
Few thousands a day. I will do your suggestion. Thanks a lot!

**Comment by fabrijp** [comment]
Indeed Apple blocked our requests if I cleanup the curl connection. Must find another way to cleanup the App memory.
