### ISSUE TITLE
APNs response 'TooManyProviderTokenUpdates'

### ISSUE THREAD

**Issue by andrew804** [matthijs2704/vapor-apns#60]
I know this might not seem like an issue with vaporAPNS but I'm feeling as though it could be.

The other day I was testing push notifications locally on my Mac and I started getting status: '429', response: 'TooManyProviderTokenUpdates' back from APNs. I wasn't really sure what this response actually meant but I found out that it basically means one notification is being sent multiple times to the same device token. https://forums.developer.apple.com/thread/86288?q=toomany

I checked my code and verified that I was not accidentally doing this. I noticed that it happens when a particular event in my app triggers two notification to be sent; 1 notification to user A and 1 to user B.
Generally the first notification to be sent (to user A) succeeds. The second notification always fails.

So I did a test where I reinitialized vaporAPNS after sending the first notification but before sending the second one. 
`// send notification to user A`
`vaporAPNS = try VaporAPNS(options: options)`
`// send notification to user B`

This solved the problem and both notifications were continuously being successfully delivered.

Could it be possible that some state is not being properly cleared and transferring between the successive curl operations in the send func?

**Comment by SupaBasti** [comment]
yes, I faced the same problems. Messages were always sent to the first token.
I needed to instantiate a new vaporAPNS = try VaporAPNS(options: options) inside the loop going over all tokens.
Would be good to fix it

**Comment by mipstian** [comment]
Same here – it was working fine until recently, but now after 2 notifications everything else fails with a 429.

**Comment by mipstian** [comment]
I've realized that for every instance of VaporAPNS (at least if used to `.send()`), a connection to Apple's servers is created and never torn down. So after a 1000 pushes or so, I start getting errors like:
`Server error: accept(Socket failed with code 24 ("Too many open files") [acceptFailed])`
And sure enough, `lsof` shows my vapor binary has 1000 open https connections to `api.push.apple.com`.

So this workaround doesn't really work unless the number of pushes is small. I'm gonna try to figure out what goes wrong when using a single VaporAPNS instance, but if you know anything that isn't here please comment!

**Comment by SupaBasti** [comment]
in VaporAPNS.swift there are two commented lines with //curl_easy_cleanup(curlHandle)
Would it help for the workaround to avoid too many open files when commenting them in?

**Comment by mipstian** [comment]
@SupaBasti I don’t think so; I’ve tried adding a deinit that calls that function (which is how the documentation states it should be used), but no difference.
At this point I’d rather fix the intended use case (one VaporAPNS instance) than the workaround anyway. Given how curl works internally and that reusing connections to APNS servers is encouraged, this might very well be the only option.

**Comment by SupaBasti** [comment]
I hope the use can can be fixed quickly. Or is there an alternative? Could https://github.com/PerfectlySoft/Perfect-Notifications be used along with Vapor?

**Comment by andrew804** [comment]
@mipstian I agree, fixing the underlying issue with curl is the way to go. I would offer to help but my knowledge of curl is not great.

**Comment by mipstian** [comment]
Fixed in #62. If you want to use my fork before this gets merged, replace the VaporAPNS line in your `Package.swift` with:
`.Package(url: "https://github.com/mipstian/vapor-apns.git", majorVersion: 2, minor: 1)`

**Comment by andrew804** [comment]
Nice one!

**Comment by SupaBasti** [comment]
works great, thanks a lot for fixing it
