### ISSUE TITLE
Support Vapor3?

### ISSUE THREAD

**Issue by MihaelIsaev** [matthijs2704/vapor-apns#69]
Please please please! As it works on HTTP1 please convert it to Vapor3? Or if you don't want to then maybe I can do that with your permission and will send a pull request?

**Comment by mxcl** [comment]
Sadly, this project is clearly dead.

Double sadly since the Vapor thread asking for this feature was closed because “matthijs2704 was doing such a good job”, HMMMMMMMM.

**Comment by MihaelIsaev** [comment]
Yeah,thank you, I wrote my own lib but for Firebase http://github.com/MihaelIsaev/FCM
